/**
 * main.tsx
 *
 * Application entry point generated by Vite.
 * Imports the global CSS (which loads Instrument Serif and the CSS reset)
 * then mounts the root <App /> component into the #root div.
 */

import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);